name: Update Kaggle Notebook

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Kaggle API
        run: pip install kaggle

      - name: Configurar credenciais do Kaggle
        run: |
          mkdir -p ~/.kaggle
cat <<EOF > ~/.kaggle/kaggle.json
${{ secrets.KAGGLE_JSON }}
EOF
          chmod 600 ~/.kaggle/kaggle.json

      - name: Enviar nova versão para o Kaggle
        run: kaggle kernels push
